# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(478, 406)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 20, 196, 194))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.surname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.surname.setObjectName("surname")
        self.horizontalLayout.addWidget(self.surname)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.internistaradio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.internistaradio.setChecked(True)
        self.internistaradio.setObjectName("internistaradio")
        self.verticalLayout_2.addWidget(self.internistaradio)
        self.pediatraradio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.pediatraradio.setObjectName("pediatraradio")
        self.verticalLayout_2.addWidget(self.pediatraradio)
        self.dermatologradio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.dermatologradio.setObjectName("dermatologradio")
        self.verticalLayout_2.addWidget(self.dermatologradio)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.isPrivateReservationCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.isPrivateReservationCheckBox.setChecked(True)
        self.isPrivateReservationCheckBox.setObjectName("isPrivateReservationCheckBox")
        self.verticalLayout.addWidget(self.isPrivateReservationCheckBox)
        self.reservationbutton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.reservationbutton.setObjectName("reservationbutton")
        self.verticalLayout.addWidget(self.reservationbutton)
        self.result = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.result.setText("")
        self.result.setScaledContents(True)
        self.result.setWordWrap(True)
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Imie"))
        self.label_2.setText(_translate("Dialog", "Nazwisko"))
        self.internistaradio.setText(_translate("Dialog", "Internista"))
        self.pediatraradio.setText(_translate("Dialog", "Pediatra"))
        self.dermatologradio.setText(_translate("Dialog", "Dermatolog"))
        self.isPrivateReservationCheckBox.setText(_translate("Dialog", "Wizyta prywatna"))
        self.reservationbutton.setText(_translate("Dialog", "rezerwuj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
